version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 10s
      retries: 5
    ports:
      - "5433:5432"

  webserver:
    image: apache/airflow:2.4.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "L8OMqisXoJ3CgOtG1caOoBrFBnEkaOZlQcIDVwrSRLM="
      AIRFLOW__WEBSERVER__SECRET_KEY: "L8OMqisXoJ3CgOtG1caOoBrFBnEkaOZlQcIDVwrSRLM="
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install python-dotenv &&
               airflow webserver"

  scheduler:
    image: apache/airflow:2.4.1
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "L8OMqisXoJ3CgOtG1caOoBrFBnEkaOZlQcIDVwrSRLM="
      AIRFLOW__WEBSERVER__SECRET_KEY: "L8OMqisXoJ3CgOtG1caOoBrFBnEkaOZlQcIDVwrSRLM="
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      - webserver
    command: >
      bash -c "pip install python-dotenv &&
               airflow scheduler"

volumes:
  postgres_db:
  airflow_logs:
